spring:
  profiles:
    active: local 
         
# local 환경
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    data: classpath:data-h2.sql 
  h2:
      console:
         enabled: true
         path: /h2
# redis
---         
spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local